[package]
name = "downloader"
version = "1.2.1"
edition = "2024"

[dependencies]
dirs = "6.0.0"
tokio = { version = "1.50.0", features = ["full"] }
reqwest = { version = "0.12.28", features = ["json", "rustls-tls"] }
indicatif = "0.18.4"
futures = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
image = "0.25.10"
imageproc = "0.26.1"
ab_glyph = "0.2.32"
uuid = { version = "1.23.1", features = ["v4"] }
num_cpus = "1.17.0"
serde_json = "1.0.149"

