[versions]
agp = "9.2.0"
rikka = "4.4.0"
hiddenapibypass = "6.1"
jLib = "104.2.28"
lifecycleService = "2.10.0"

[plugins]
android = { id = "com.android.application", version.ref = "agp" }
rikka = { id = "dev.rikka.tools.refine", version.ref = "rikka" }

[libraries]
annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "rikka" }
annotation-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "rikka" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
j-lib = { module = "io.github.dot166:j-Lib", version.ref = "jLib" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
