/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.dot166.haosbuses

import io.github.dot166.busapi.Departure
import io.github.dot166.busapi.DepartureBoard
import io.ktor.http.HttpStatusCode
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.install
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.response.respond
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import kotlinx.serialization.Serializable
import java.time.LocalDateTime

@Serializable
data class NextBusResponse(
    val route: String,
    val direction: String,
    val scheduled: String,
    val estimated: String?
)

@Serializable
data class ErrorResponse(
    val error: String
)

fun main() {
    embeddedServer(
        Netty,
        host = "0.0.0.0",
        port = 8080
    ) {
        install(ContentNegotiation) {
            json()
        }

        routing {
            get("/next-bus") {
                val atcoCode = call.request.queryParameters["atcoCode"]

                if (atcoCode.isNullOrBlank()) {
                    call.respond(
                        HttpStatusCode.BadRequest,
                        ErrorResponse("Missing atcoCode parameter")
                    )
                    return@get
                }

                val now = LocalDateTime.now()

                println("Bus request received at $now")

                val departure = findNextDeparture(now, atcoCode)

                if (departure == null) {
                    call.respond(
                        HttpStatusCode.NotFound,
                        ErrorResponse("No buses found")
                    )
                    return@get
                }

                println(
                    "Next bus: ${departure.service} " +
                            "${departure.destination} " +
                            (departure.expected ?: departure.scheduled)
                )

                call.respond(
                    NextBusResponse(
                        route = departure.service,
                        direction = departure.destination,
                        scheduled = departure.scheduled,
                        estimated = departure.expected
                    )
                )
            }
        }
    }.start(wait = true)
}

private suspend fun findNextDeparture(
    now: LocalDateTime,
    atcoCode: String
): Departure? {

    // First, ask for today's departures.
    val today = DepartureBoard(atcoCode)
        .getNextDepartures(now)
        .firstOrNull()

    if (today != null) {
        return today
    }

    // No more buses today. Ask for tomorrow.
    val tomorrow = now
        .toLocalDate()
        .plusDays(1)
        .atStartOfDay()

    return DepartureBoard(atcoCode)
        .getNextDepartures(tomorrow)
        .firstOrNull()
}