# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

wallpaper {
    monitor =
    path = $HOME/wall.jpg
}

splash = false
