name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test_downloader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3

      - name: Test Downloader
        run: cd downloader && cargo run ./test-songs.txt
