name: Tests

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  GH_AUTH_TOKEN: ${{ secrets.GH_TOKEN }} # setting GH_TOKEN for the entire workflow

jobs:
  filter-paths:
    runs-on: ubuntu-latest
    outputs:
      downloader_modified: ${{ steps.filter.outputs.downloader_modified }}
      utau_stuff_modified: ${{ steps.filter.outputs.utau_stuff_modified }}
      nightstand_modified: ${{ steps.filter.outputs.nightstand_modified }}
      aosp_modified: ${{ steps.filter.outputs.aosp_modified }}
    steps:
    - uses: actions/checkout@v6
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          downloader_modified:
            - 'downloader/**'
            - '.github/**'
          utau_stuff_modified:
            - 'UTAU/**'
            - '.github/**'
          nightstand_modified:
            - 'nightstand/**'
            - '.github/**'
          aosp_modified:
            - 'aosp/source/**'
            - '.github/**'

  test_downloader:
    needs: filter-paths
    if: needs.filter-paths.outputs.downloader_modified == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3

      - name: Test Downloader
        run: cd downloader && cargo run ./test-songs.txt

  test_libmomone:
    needs: filter-paths
    if: needs.filter-paths.outputs.utau_stuff_modified == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Test LibMomone
        run: cd UTAU/libmomone && cargo test

  build_nightstand:
    needs: filter-paths
    if: needs.filter-paths.outputs.nightstand_modified == 'true'
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    
    - name: Setup JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: 17
        cache: 'gradle'

    - name: Build NightStand
      run: cd nightstand && chmod +x gradlew && ./gradlew assembleRelease

  ci-tool:
    needs: filter-paths
    if: needs.filter-paths.outputs.aosp_modified == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Run CI Tool
      run: |
       cd aosp/source/ci-tool
       cargo update
       cargo run --release

