name: Tests

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  GH_AUTH_TOKEN: ${{ secrets.GH_TOKEN }} # setting GH_TOKEN for the entire workflow

jobs:
  build-it-all:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3

      - name: Test Downloader
        run: cd downloader && cargo run ./test-songs.txt
      - name: Test LibMomone
        run: cd UTAU/libmomone && cargo test
      - name: Build LockDate
        run: cd lockdate && cargo build
      - name: Build rsTunes
        run: cd rsTunes-AOSP && cargo build
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Build NightStand
        run: cd nightstand && chmod +x gradlew && ./gradlew assembleRelease
      - name: Check if Release build
        shell: sh
        run: |
          VERSION=$(jq '.elements[0].versionCode' nightstand/app/build/outputs/apk/release/output-metadata.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          RELEASE=0 && git show-ref --tags --verify --quiet "refs/tags/nightstand-$VERSION" || RELEASE=1
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
      - name: send to repo and prebuilt
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' && env.RELEASE == '1' }}
        run: |
          cd nightstand
          echo "${{ secrets.KEYSTORE }}" > a.txt
          base64 -d a.txt > key.jks
          echo "${{ secrets.KEYSTORE_PROPS }}" > b.txt
          base64 -d b.txt > keystore.properties
          ./gradlew assembleRelease # rebuild so it is actually signed
          echo ${{ env.VERSION }}
          mkdir -p artifacts/apps/packages/io.github.dot166.nightstand/${{ env.VERSION }}
          echo "channel = \"stable"\" > artifacts/apps/packages/io.github.dot166.nightstand/${{ env.VERSION }}/channel.toml
          cp app/build/outputs/apk/release/app-release.apk artifacts/apps/packages/io.github.dot166.nightstand/${{ env.VERSION }}/base.apk
          cp app/build/outputs/apk/release/app-release.apk.idsig artifacts/apps/packages/io.github.dot166.nightstand/${{ env.VERSION }}/base.apk.idsig
          git lfs install
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/dot166/apks.git apks
          cd apks
          git lfs pull
          cd ..
          cp -r artifacts/* apks/
          cd apks
          git add .
          git commit -m "NightStand ${{ env.VERSION }}"
          git push origin
          cd ..
          rm -rf artifacts
          rm -rf apks
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/dot166/platform_external_NightStand.git prebuilt
          cp app/build/outputs/apk/release/app-release.apk prebuilt/prebuilt/
          cp app/build/outputs/apk/release/app-release.apk.idsig prebuilt/prebuilt/
          cd prebuilt
          git add .
          git commit -m "NightStand ${{ env.VERSION }}"
          git push origin
          cd ..
          rm -rf prebuilt
          rm -rf a.txt
          rm -rf b.txt
          rm -rf key.jks
          rm -rf keystore.properties
      - name: Upload to new Release
        uses: softprops/action-gh-release@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' && env.RELEASE == '1' }}
        with:
          tag_name: nightstand-${{ env.VERSION }}
          make_latest: true
          generate_release_notes: true
      - name: Run CI Tool
        run: |
         cd aosp/source/ci-tool
         cargo update
         cargo run --release

      - name: Update Helpline List
        run: |
          cd sensitive-pn/etc
          curl -O https://raw.githubusercontent.com/LineageOS/android_vendor_lineage/refs/heads/lineage-23.2/prebuilt/common/etc/sensitive_pn.xml
          cd ../../..

      - name: Commit changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' }}
        run: |
          git add .
          git commit -m "Update Helpline List" || true

      - name: Build libPhone2
        run: cd sensitive-pn/libPhone2 && chmod +x gradlew && ./gradlew assembleRelease
      - name: Check if Release build
        shell: sh
        run: |
          VERSION=$(cat sensitive-pn/libPhone2/ver)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          RELEASE=0 && git show-ref --tags --verify --quiet "refs/tags/libPhone2-$VERSION" || RELEASE=1
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV

      - name: publish libPhone2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' && env.RELEASE == '1' }}
        run: |
          cd sensitive-pn/libPhone2
          echo ${{ env.VERSION }}
          ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache

      - name: add AOSP prebuilt
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' }}
        run: |
          cd sensitive-pn/libPhone2
          cp lib/build/outputs/aar/lib-release.aar lib/libPhone2.aar
          git add .
          git commit -m "Update libPhone2" || true

      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' }}
        with:
          branch: ${{ github.ref }}

      - name: Upload to new Release
        uses: softprops/action-gh-release@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' && env.RELEASE == '1' }}
        with:
          tag_name: libPhone2-${{ env.VERSION }}
          make_latest: true
          generate_release_notes: true

      - name: Build LibLauncher3
        run: cd LibLauncher3 && chmod +x gradlew && ./gradlew assembleRelease && ./gradlew generateBp --no-configuration-cache

      - name: Commit changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' }}
        run: |
          git add .
          git commit -m "Update generated files" || true

      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' }}
        with:
          branch: ${{ github.ref }}
      - name: Check if Release build
        shell: sh
        run: |
          VERSION=$(cat LibLauncher3/ver)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          RELEASE=0 && git show-ref --tags --verify --quiet "refs/tags/LibLauncher3-$VERSION" || RELEASE=1
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV

      - name: publish LibLauncher3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' && env.RELEASE == '1' }}
        run: |
          cd LibLauncher3
          echo ${{ env.VERSION }}
          ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache

      - name: Upload to new Release
        uses: softprops/action-gh-release@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'dot166/misc' && env.RELEASE == '1' }}
        with:
          tag_name: LibLauncher3-${{ env.VERSION }}
          make_latest: true
          generate_release_notes: true

